version: "3.9"

volumes:
  database:
    driver: local

services:
  openai-bot:
    container_name: openai-bot
    image: openai-bot:latest
    environment:
      - TELEGRAM_TOKEN=TOKEN
      - OPENAI_API_KEY=KEY
      - DBPATH=/app/data/local.sqlite
      - BOT_NAME=NAME
    volumes:
      - ./database/:/app/data
